config/routes.rb
Rewsly::Application.routes.draw do
	resources :stories, only: [:index, :show, :new, :create]
  root "stories#index"
  get "search", to: "search#index"
end

app/models/story.rb
class Story < ActiveRecord::Base
	validates :title, :category, :link, presence: true
	validates :upvotes, numericality: { only_integer: true }
	
	def self.search_for(query)
		self.where('title LIKE :query OR category LIKE :query', query: "%#{query}%")
	end

	def self.upvote
		self.upvote += 1
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	# assigns so that the users input is 
  	# used as the query
  	query = params['q']   
  	# Using the method search_for, 
  	# which is defined in the model 
  	@stories = Story.search_for query 
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController 
  def index
  	@stories = Story.all
  end 	

  def show
  	find_story
  end

  def new
  	@story = Story.new
  end

  def create
  	@story = Story.create safe_story
  	if @story.save 
  		redirect_to story
  	else
  		render 'new'
  	end
  end

  private 

  def find_story
  	@story = Story.find(params[:id])
  end

  def safe_story
  	params.require(:story).permit(:title, :link, :upvotes, :category)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewsly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<!-- replace this with the partial -->
<% @stories.each do |story| %>
	<p><h3><%= story.title %></h3></p>
	<p>Category: <%= story.category %></p>
	<p>Upvotes: <%= story.upvotes %></p>
	<p><%= link_to 'Original Site', story.link %></p>
<% end %>

app/views/stories/_stories.html.erb
<% @story.each do |story| %>
	<p><h3><%= story.title %></h3></p>
	<p>Category: <%= story.category %></p>
	<p>Upvotes: <%= story.upvotes %></p>
	<p><%= link_to 'Original Site', story.link %></p>
<% end %>

app/views/stories/index.html.erb
<h1>Welcome to Rewsly</h1>

<p>
<%= form_tag '/search', method: :get do %> 
	<%= label_tag 'q', "Search" %>
	<%= text_field_tag 'q' %>
	<%= submit_tag "Search" %>
<% end %>
</p>
<p>
	<%= link_to 'Add a New Story!', new_story_path %>
</p>

<p>
<table>
	<tr>
		<th>Stories</th>
	</tr>
	<% @stories.each do |story| %>
		<tr>
			<td><%= link_to "#{story.title}", story %></td>
		</tr>
	<% end %>
</table>
</p>

app/views/stories/new.html.erb
<%= form_for @story do |f| %>
<% if @story.errors.any? %>
	<div id="error explanation">
		<h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from saving:</h2>
		<ul>
			<% @story.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
		<% end %>

	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>
	<p><%= f.label :link %></p>
	<p><%= f.text_field :link %></p>
	<p><%= f.label :category %></p>
	<p><%= f.text_field :category %></p>
	<p><%= f.label :upvotes %></p>
	<p><%= f.text_field :upvotes %></p>
	<p><%= f.button %></p>
<% end %>

app/views/stories/show.html.erb
	<p><h3><%= @story.title %></h3></p>
	<p>Category: <%= @story.category %></p>
	<p>Upvotes: <%= @story.upvotes %></p>
	<p><%= link_to 'Original Site', @story.link %></p>